---
- name: Bootstrap CloudMan Node
  hosts: all
  become: yes
  gather_facts: False
  pre_tasks:
    - name: Install Python2 if not available
      vars:
        - ansible_python_interpreter: /usr/bin/python3
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      retries: 30
      delay: 10
    - setup: # aka gather_facts
  tasks:
    - name: Check if Docker is installed
      command: docker
      register: docker_installed
      ignore_errors: True

    - name: Install Docker
      include_role:
        name: docker
      vars:
        docker_users:
          - ubuntu
      when: "docker_installed is failed"

    - name: Install system packages
      package:
        name: "python-pip"
        state: present
      register: pkg_result
      until: pkg_result is success
      retries: 30
      delay: 10

    - name: Install pip modules
      pip:
        name: ['docker-py']
        state: present

    # Note that this task does not wait for the container to exit/end execution
    - name: Boot CloudMan Node
      shell: "{{ rancher_node_command }}"
...
